In [26]:
import numpy as np
import pandas as pd

#### Creating a DataFrame

In [27]:

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [28]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
col = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=col)

In [30]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selection and indexing of Columns

In [31]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [32]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [33]:
# if I want to choose multiple column then 
df2[["Name", "Salary"]]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

#### Creating a new column

In [34]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [36]:
df2["Gender"] = ["Male", "Female", "Male", "Female"]

In [16]:
df2

    Name  Age      City  Salary  Gender
0   John   28  New York   65000    Male
1   Anna   34     Paris   70000  Female
2  Peter   29    Berlin   62000    Male
3  Linda   42    London   85000  Female

#### Removing Columns

In [37]:
df2

    Name  Age      City  Salary  Gender
0   John   28  New York   65000    Male
1   Anna   34     Paris   70000  Female
2  Peter   29    Berlin   62000    Male
3  Linda   42    London   85000  Female

In [38]:
df2.drop(["City", "Salary"], axis=1) # inplace = True is for permanently delete

    Name  Age  Gender
0   John   28    Male
1   Anna   34  Female
2  Peter   29    Male
3  Linda   42  Female

In [39]:
df2

    Name  Age      City  Salary  Gender
0   John   28  New York   65000    Male
1   Anna   34     Paris   70000  Female
2  Peter   29    Berlin   62000    Male
3  Linda   42    London   85000  Female

In [40]:
# now If I want to delete a row then

In [41]:
df2.drop(0, axis=0)

    Name  Age    City  Salary  Gender
1   Anna   34   Paris   70000  Female
2  Peter   29  Berlin   62000    Male
3  Linda   42  London   85000  Female

#### Selecting Rows

In [42]:
df2

    Name  Age      City  Salary  Gender
0   John   28  New York   65000    Male
1   Anna   34     Paris   70000  Female
2  Peter   29    Berlin   62000    Male
3  Linda   42    London   85000  Female

In [45]:
# loc is use for selecting rows in panda
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Gender        Male
Name: 0, dtype: object

In [47]:
# for selecting multiple rows in pandas
df2.loc[[0,3]]

    Name  Age      City  Salary  Gender
0   John   28  New York   65000    Male
3  Linda   42    London   85000  Female

#### Selecting Subsets of Rows and Columns

In [48]:
df2

    Name  Age      City  Salary  Gender
0   John   28  New York   65000    Male
1   Anna   34     Paris   70000  Female
2  Peter   29    Berlin   62000    Male
3  Linda   42    London   85000  Female

In [50]:
# suppose we need to select only label 1,2 inside data Name and Salary only
df2.loc[[1,2]][["Name", "Salary"]]

    Name  Salary
1   Anna   70000
2  Peter   62000

#### Conditional Selection

In [51]:
df2

    Name  Age      City  Salary  Gender
0   John   28  New York   65000    Male
1   Anna   34     Paris   70000  Female
2  Peter   29    Berlin   62000    Male
3  Linda   42    London   85000  Female

In [52]:
# I only want to see those people who are above only 30 age
df2[df2["Age"] > 30]

    Name  Age    City  Salary  Gender
1   Anna   34   Paris   70000  Female
3  Linda   42  London   85000  Female

In [54]:
# I only want to see those people who are above only 30 age and city = paris
df2[(df2["Age"] > 30) & (df2['City'] == "Paris")]

   Name  Age   City  Salary  Gender
1  Anna   34  Paris   70000  Female