In [5]:
import numpy as np 
import pandas as pd

#### Finding Missing Data

In [8]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [9]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [11]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [12]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

#### Removing Missing Data

In [13]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [14]:
df.dropna() # only given the row where no nan value exits

     A  B    C    D
0  1.0  1  1.0  1.0

In [15]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [17]:
df.dropna(thresh=3) # thresh=3 mean return remove rows where not atleat 3 elements not exists

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [18]:
df.dropna(thresh=4) # means retun row where 4 elements are exits and all rows are removed

     A  B    C    D
0  1.0  1  1.0  1.0

#### Filling The Missing Data

In [21]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [22]:
df.fillna(0) # means fill all the NaN elements with 0 value

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [23]:
# now we can also fill the NaN value with our custom Value
new_value = {"A": 0, "B":100, "C":300, "D": 500}
df.fillna(value=new_value)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  500.0
2  0.0  3    3.0  500.0
3  4.0  4  300.0  500.0
4  5.0  5  300.0    5.0

In [24]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [25]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0